### ISSUE TITLE
Prework module order

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/programming-mindset-introduction-to-programming-mindset#2]
Is the programming mindset unit supposed to come after all of the Ruby lessons? It seems like it's supposed to be relatively early in the prework modules.

**Comment by maxwellbenton** [comment]
Hi @PeteHanner,

Thank you for providing feedback on this lesson. Because this section builds off some of core coding concepts and refers to some things like Arrays and Hashes, it is intended to go after the core Ruby lessons in Prework. However, this lesson was phrased to imply otherwise, so we've updated the content to avoid confusion in the future and we do welcome this sort of feedback and are currently reviewing the position of this section to see if it better fits a little earlier in the Ruby content.
